version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '8080:8000'
    volumes:
      - .:/var/www/html
    entrypoint: |
      bash -c "
      set -e 
      set -x
      echo '[DEV] Conectando a la base de datos...'
      while ! mysql -h db -uroot -p'$MYSQL_ROOT_PASSWORD' -e 'SHOW DATABASES;' >/dev/null 2>&1; do
        echo 'Waiting for MySQL server to be available...'
        sleep 5
      done
      
      echo '[DEV] Base de datos disponible.'
      echo '[DEV] Creando/actualizando tablas...'
      python3 manage.py migrate

      echo '[DEV] Lanzando tests para comprobar que todo funciona correctamente'
      pytest
      
      echo '[DEV] Iniciando el servidor...'
      exec python3 manage.py runserver 0.0.0.0:8000
      "
    depends_on:
        - db
    networks:
      network:
        ipv4_address: 172.18.10.5
  db:
    image: mysql:8.0.11
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3308:3306'
    networks:
      network:
        ipv4_address: 172.18.10.6
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.10.0/16
          gateway: 172.18.10.0