version: '3.3'
services:
  db:
    image: mysql:8.0.11
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3308:3306'