# Generated by Django 5.0.2 on 2024-04-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='articles',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_with_taxes',
            new_name='taxes',
        ),
    ]
